config/routes.rb
Rails.application.routes.draw do
  get 'messages/create'
  devise_for :users
  resources :chatrooms
  resources :messages, only: [:create]

  root 'chatrooms#index'  

  mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  has_many :messages
  belongs_to :user
  validates :name, presence: true
  validates :user, presence: true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :chatroom

  after_create_commit{
    BroadcastMessageJob.perform_later(self)
  }
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, uniqueness: true, presence: true
  validates :email, uniqueness: true, presence: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :messages

  scope :active, -> { where(active: true)}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!
	before_action :configure_permitted_parameters, if: :devise_controller?

	protected

	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
	end
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
	before_action :set_chatroom, only: [:show, :destroy]
  def index
  	@chatrooms = Chatroom.all
  end

  def show
  end

  def create
  	@chatroom = Chatroom.new permitted_params
    @chatroom.user = current_user
    @chatroom.save
  end

  def destroy
  	@chatroom.delete
  end

  private

  def set_chatroom
  	@chatroom = Chatroom.find(params[:id])
  end

  def permitted_params
  	params.require(:chatroom).permit(:name)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
  	@message = Message.new permitted_params
  	@message.user = current_user
  	@message.save!
  end

  private

  def permitted_params
  	params.require(:message).permit(:msg, :chatroom_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chatrooms_helper.rb
module ChatroomsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/chatrooms/_chatroom_item.erb
<div data-id="<%= chatroom.id %>" class="chatroom">
	<% if chatroom.user == current_user %>
		<%= link_to "x", chatroom_path(chatroom), method: :delete, remote: true, class: 'close' %>
	<% end %>
	<%= link_to chatroom.name, chatroom_path(chatroom), method: :get, class: 'chatroom-link' %>
</div>

app/views/chatrooms/create.html.erb
<h1>Chatrooms#create</h1>
<p>Find me in app/views/chatrooms/create.html.erb</p>

app/views/chatrooms/create.js.erb
// const chatrooms = document.querySelector(".chatrooms")
// chatrooms.append(<%= j render(partial: 'chatrooms/chatroom_item', locals: { chatroom: @chatroom }) %>)

$('.chatrooms').append("<%= j render(partial: 'chatrooms/chatroom_item', locals: { chatroom: @chatroom }) %>")
$('#chatroom_name').val("")

app/views/chatrooms/destroy.js.erb
$("div[data-id='<%= @chatroom.id %>']").remove()

app/views/chatrooms/index.html.erb
<div class="custom-content-container">
  <div class="row">
		<div class="col-3">
			<%= render partial: "shared/users" %>
		</div>
		<div class="col">
			<div class="chatroom-header-wrapper">
				<p class="chatroom-header">ChatRooms</p>
			</div>

			<div class="chatrooms">
				<% @chatrooms.each do |chatroom| %>
			    <%= render "chatrooms/chatroom_item", chatroom: chatroom %>
				<% end %>
			</div>

			<%= simple_form_for Chatroom.new, remote: true do |form| %>
			  <%= form.input :name, placeholder: 'Create A Chatroom', label: false %>
			<% end %>
		</div>  	
  </div>
</div>

app/views/chatrooms/show.html.erb
<div class="custom-content-container">
	<div class="row">
		<div class="col-3">
			<%= render partial: 'shared/users' %>
		</div>
		<div class="col">
			<div class="chatroom-header-wrapper">
				<p class="chatroom-header"><%= @chatroom.name %></p>
			</div>

			<div class="messages" data-room="<%= @chatroom.id %>">
				<% @chatroom.messages.each do |message| %>
				  <%= render "/messages/message", message: message %>
				<% end %>
			</div>

			<%= simple_form_for Message.new, remote: true do |form| %>
		     <%= form.input :msg, label: false, placeholder: "Insert personality here ;)" %>
		     <%= form.hidden_field :chatroom_id, value: @chatroom.id %>
			<% end %>
    </div>
	</div>
</div>
	
	

<%= javascript_pack_tag "chatrooms.js" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChatApplication</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'shared/navbar' %>

    <%= yield %>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="message">
  <%= message.user.username %>:<%= message.msg %>
</div>

app/views/messages/create.js.erb
$('#message_msg').val('')

app/views/shared/_navbar.html.erb
<div class="light-navbar">
  <ul class="navbar-list">
    <% if current_user %>
      <li>Signed in as: <%= current_user.username %></li>
      <li><%= link_to "Chatrooms", root_path %></li>
      <li><%= link_to "Sign Out", destroy_user_session_path, method: 'delete' %></li>      
    <% else %>
      <li><%= link_to "Sign In", new_user_session_path %></li>
    <% end %>
  </ul>
</div>

app/views/shared/_user.html.erb
<li data-userid="<%= user.id %>"><%= user.username %></li>

app/views/shared/_users.html.erb
<div class="active-users-wrapper">
	<p class="active-users">Active Users</p>
	<div id="userList" class="col-4">
		<% User.active.each do |user| %>
		  <%= render partial: "shared/user", locals: {user: user} if user != current_user %>
		<% end %>
	</div>
</div>

<%= javascript_pack_tag "users" %>